version: '3'

services:
    flemme-docker:
        container_name: flemme-docker
        image: php:7.2.8-cli
        volumes:
            - ./:/var/www
        ports:
            - "77:80"
        links:
            - db:db
        depends_on:
            - db
    db:
        image: mysql:5.6
        volumes:
            - ./mysql:/var/lib/mysql
        ports:
            - "3307:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=root
    myadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - "7777:80"
        links:
            - db:db
        depends_on:
- db
