version: '3'

services:
    cmapi-docker:
        container_name: cmapi-docker
        image: tommylau/php-5.2
        volumes:
            - ~/Bureau/Docker_CMAPI/code:/var/www
        ports:
            - "80:80"
        links:
            - db:db
        depends_on:
            - db
    db:
        image: mysql:5.5
        volumes:
            - ~/Bureau/Docker_CMAPI/mysql:/var/lib/mysql
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=root
    myadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - "8080:80"
        links:
            - db:db
        depends_on:
            - db
